/realsense_d435i:
  ros__parameters:
    enable_color: false
    enable_depth: false
    enable_infra1: true
    enable_gyro: true
    enable_accel: true
    unite_imu_method: 2
    json_file_path: "/config/advanced.json"
