services:

  rviz:
    extends:
      service: realsense
    image: "rviz:latest"
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    command: ros2 run rviz2 rviz2

  charuco-calibration:
    extends:
      service: realsense
    image: "charuco_calibration:latest"
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    command: >
      ros2 run camera_calibration cameracalibrator
      --no-service-check
      --square 0.0320
      --pattern charuco
      --size 5x7
      --charuco_marker_size 0.0246
      --aruco_dict 6x6_250
      --ros-args
      --remap image:=/camera/image_raw
      --remap camera:=/camera

  checkerboard-calibration:
    extends:
      service: realsense
    image: "checkerboard_calibration:latest"
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    command: >
      ros2 run camera_calibration cameracalibrator
      --no-service-check
      --size 5x8
      --square 0.0257
      --ros-args
      --remap image:=/camera/image_raw
      --remap camera:=/camera

  cam2image:
    build: 
      context: .
      dockerfile: camera.Dockerfile
      args:
        - USER_UID=1001
        - USER_GID=1001
        - USERNAME=${USERNAME}
    image: "cam2image:latest"
    network_mode: host
    ipc: host
    init: true
    privileged: true
    environment:
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    command: >
      ros2 run image_tools cam2image --ros-args 
      --params-file /config/cam2image_params.yaml
      -r /image:=/camera/image_raw
      --log-level warn

  realsense:
    build: 
      context: .
      dockerfile: camera.Dockerfile
      args:
        - USER_UID=1001
        - USER_GID=1001
        - USERNAME=${USERNAME}
    image: "realsense:latest"
    network_mode: host
    ipc: host
    init: true
    privileged: true
    environment:
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command: >
      ros2 run realsense2_camera realsense2_camera_node
      --ros-args
      -r __node:=camera
      -r __ns:=/
      -r /camera/infra1/image_rect_raw:=/camera/image_raw
      -r /camera/infra1/camera_info:=/camera/camera_info
      -p enable_color:=false
      -p enable_depth:=false
      -p enable_infra1:=true
      -p enable_gyro:=true
      -p enable_accel:=true
      -p unite_imu_method:=2
      -p json_file_path:=/config/advanced.json
