services:

  rviz:
    extends:
      service: realsense
    image: "rviz:latest"
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    command: ros2 run rviz2 rviz2

  charuco-calibration:
    extends:
      service: realsense
    image: "charuco_calibration:latest"
    volumes:
      - ./calibration_data:/calibration_data
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    command: >
      bash -c "source /ros_ws/install/setup.bash && ros2 launch /launch.py calibration_board:=charuco output_path:=/calibration_data"

  checkerboard-calibration:
    extends:
      service: realsense
    image: "checkerboard_calibration:latest"
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: ${DISPLAY}
    command: >
      ros2 launch /launch.py calibration_board:=checkerboard

  cam2image:
    build: 
      context: .
      dockerfile: camera.Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
        - USERNAME=${USERNAME}
    image: "cam2image:latest"
    network_mode: host
    ipc: host
    init: true
    privileged: true
    environment:
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./launch.py:/launch.py
      - ./params/:/params/
    command: >
      ros2 launch /launch.py use_cam2image:=true

  realsense:
    build: 
      context: .
      dockerfile: camera.Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
        - USERNAME=${USERNAME}
    image: "realsense:latest"
    network_mode: host
    ipc: host
    init: true
    privileged: true
    environment:
      FASTDDS_BUILTIN_TRANSPORTS: UDPv4
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./launch.py:/launch.py
      - ./params/:/params/
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command: >
      ros2 launch /launch.py use_realsense:=true
